### PR TITLE
fix download uefi-ntfs.img 

### PR DESCRIPTION
**Pull request by FuPeiJiang**
download the FILE, not the folder(I think it downloads the html page https://github.com/pbatard/rufus/tree/master/res/uefi)

change:
https://github.com/pbatard/rufus/raw/master/res/uefi/
to
https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img

### CODE REVIEW

**Review by WaxyMocha — APPROVED** [review]

**Comment by WaxyMocha** [comment]
Ok so I checked this part of code and turns out that in general, I don't think it does anything. You are right that current code downloads html instead of image, but then it is copied to /dev/sdx2 and that doesn't make sense. One more reason to refactor the whole thing.
Thanks for PR :)

**Comment by WaxyMocha** [comment]
No, wait. If it's just raw image, it does make sense to copy it directly to block device.

**Comment by FuPeiJiang** [comment]
this works
`sudo dd if="/path/to/uefi-ntfs.img" of=/dev/sdX2`
but it's dd, so it's dangerous,


python does a copy, which is less dangerous than overwrite, but it would require mounting `"/path/to/uefi-ntfs.img"` AND mounting `/dev/sdX2`

**Comment by FuPeiJiang** [comment]
I have more commits, 

but since: [CONTRIBUTING.md](https://github.com/WoeUSB/WoeUSB-ng/blob/master/CONTRIBUTING.md#user-content-create-commits-based-on-minimal-independent-changes)
>Create commits based on minimal independent changes
Avoid creating commits that do multiple things at once as this will help other developers understand the change history.

I guess pull requests shouldn't contain unrelated stuff, so I started with this one

**Pull request merged**
